/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxh_audiovideolearning_jnidemo_Mp3Encoder */

#ifndef _Included_com_zxh_audiovideolearning_jnidemo_Mp3Encoder
#define _Included_com_zxh_audiovideolearning_jnidemo_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxh_audiovideolearning_jnidemo_Mp3Encoder
 * Method:    encode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zxh_audiovideolearning_jnidemo_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
